using Apex.Core.Models;
using System;
using System.Collections.Generic;

namespace Apex.Services
{
    /// <summary>
    /// Service for calculating print job quotations and pricing.
    /// </summary>
    public class QuotationService
    {
        /// <summary>
        /// Creates a quick quotation for a simple print job.
        /// </summary>
        public PrintJobQuotation CreateQuickQuote(
            int pages,
            bool doubleSided,
            int quantity,
            decimal pricePerSheet)
        {
            var quote = new PrintJobQuotation
            {
                TotalPages = pages,
                IsDoubleSided = doubleSided,
                Quantity = quantity,
                PricePerSheet = pricePerSheet
            };
            
            quote.Calculate();
            return quote;
        }
        
        /// <summary>
        /// Creates a full quotation with cover and finishing services.
        /// </summary>
        public PrintJobQuotation CreateFullQuote(
            int pages,
            bool doubleSided,
            int quantity,
            decimal pricePerSheet,
            bool hasCover,
            decimal coverPrice,
            List<FinishingService> finishingServices,
            decimal profitMargin)
        {
            var quote = new PrintJobQuotation
            {
                TotalPages = pages,
                IsDoubleSided = doubleSided,
                Quantity = quantity,
                PricePerSheet = pricePerSheet,
                HasCover = hasCover,
                CoverPricePerPiece = coverPrice,
                FinishingServices = finishingServices ?? new List<FinishingService>(),
                ProfitMarginPercent = profitMargin
            };
            
            quote.Calculate();
            return quote;
        }
        
        /// <summary>
        /// Recalculates an existing quotation.
        /// </summary>
        public void Recalculate(PrintJobQuotation quotation)
        {
            quotation.Calculate();
        }
        
        /// <summary>
        /// Exports quotation to a formatted string for printing or saving.
        /// </summary>
        public string ExportQuotation(PrintJobQuotation quote, string customerName = "")
        {
            var header = string.IsNullOrEmpty(customerName) 
                ? "=== Print Job Quotation ===" 
                : $"=== Quotation for: {customerName} ===";
                
            return $@"
{header}
Date: {DateTime.Now:yyyy-MM-dd HH:mm}

{quote.GetBreakdown()}

---
Generated by Apex Print OS
";
        }
        
        /// <summary>
        /// Compares two pricing scenarios.
        /// </summary>
        public string CompareQuotes(PrintJobQuotation quote1, PrintJobQuotation quote2, string scenario1Name = "Scenario 1", string scenario2Name = "Scenario 2")
        {
            return $@"
=== Quotation Comparison ===

{scenario1Name}:
  Final Price: {quote1.FinalPrice:F2} EGP
  Sheets: {quote1.SheetsRequired}
  
{scenario2Name}:
  Final Price: {quote2.FinalPrice:F2} EGP
  Sheets: {quote2.SheetsRequired}
  
Difference: {Math.Abs(quote1.FinalPrice - quote2.FinalPrice):F2} EGP
Better Option: {(quote1.FinalPrice < quote2.FinalPrice ? scenario1Name : scenario2Name)}
";
        }
    }
}
