//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apex.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Apex.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string Dashboard => ResourceManager.GetString("Dashboard", resourceCulture);
        public static string Clients => ResourceManager.GetString("Clients", resourceCulture);
        public static string Orders => ResourceManager.GetString("Orders", resourceCulture);
        public static string Expenses => ResourceManager.GetString("Expenses", resourceCulture);
        public static string Attendance => ResourceManager.GetString("Attendance", resourceCulture);
        public static string PrintingOps => ResourceManager.GetString("PrintingOps", resourceCulture);
        public static string Settings => ResourceManager.GetString("Settings", resourceCulture);
        public static string Language => ResourceManager.GetString("Language", resourceCulture);
        public static string English => ResourceManager.GetString("English", resourceCulture);
        public static string Arabic => ResourceManager.GetString("Arabic", resourceCulture);
        public static string Welcome => ResourceManager.GetString("Welcome", resourceCulture);
        public static string AddClient => ResourceManager.GetString("AddClient", resourceCulture);
        public static string Name => ResourceManager.GetString("Name", resourceCulture);
        public static string Email => ResourceManager.GetString("Email", resourceCulture);
        public static string Phone => ResourceManager.GetString("Phone", resourceCulture);
        public static string Address => ResourceManager.GetString("Address", resourceCulture);
        public static string Save => ResourceManager.GetString("Save", resourceCulture);
        public static string Cancel => ResourceManager.GetString("Cancel", resourceCulture);
        public static string Delete => ResourceManager.GetString("Delete", resourceCulture);
        public static string Edit => ResourceManager.GetString("Edit", resourceCulture);
        public static string Total => ResourceManager.GetString("Total", resourceCulture);
        public static string Date => ResourceManager.GetString("Date", resourceCulture);
        public static string Status => ResourceManager.GetString("Status", resourceCulture);
        public static string GenerateInvoice => ResourceManager.GetString("GenerateInvoice", resourceCulture);
        public static string AddOrder => ResourceManager.GetString("AddOrder", resourceCulture);
        public static string Printers => ResourceManager.GetString("Printers", resourceCulture);
        public static string Jobs => ResourceManager.GetString("Jobs", resourceCulture);
        public static string AddPrinter => ResourceManager.GetString("AddPrinter", resourceCulture);
        public static string IPAddress => ResourceManager.GetString("IPAddress", resourceCulture);
        public static string Port => ResourceManager.GetString("Port", resourceCulture);
        public static string DistributeJob => ResourceManager.GetString("DistributeJob", resourceCulture);
        public static string FileName => ResourceManager.GetString("FileName", resourceCulture);
        public static string Copies => ResourceManager.GetString("Copies", resourceCulture);
        public static string CheckIn => ResourceManager.GetString("CheckIn", resourceCulture);
        public static string CheckOut => ResourceManager.GetString("CheckOut", resourceCulture);
        public static string Employee => ResourceManager.GetString("Employee", resourceCulture);
        public static string AddEmployee => ResourceManager.GetString("AddEmployee", resourceCulture);
        public static string NetProfit => ResourceManager.GetString("NetProfit", resourceCulture);
        public static string Income => ResourceManager.GetString("Income", resourceCulture);
        public static string Expense => ResourceManager.GetString("Expense", resourceCulture);
        public static string Refresh => ResourceManager.GetString("Refresh", resourceCulture);
        public static string ID => ResourceManager.GetString("ID", resourceCulture);
        public static string Type => ResourceManager.GetString("Type", resourceCulture);
        public static string Contact => ResourceManager.GetString("Contact", resourceCulture);
        public static string Client => ResourceManager.GetString("Client", resourceCulture);
        public static string From => ResourceManager.GetString("From", resourceCulture);
        public static string To => ResourceManager.GetString("To", resourceCulture);
        public static string Category => ResourceManager.GetString("Category", resourceCulture);
        public static string Description => ResourceManager.GetString("Description", resourceCulture);
        public static string Amount => ResourceManager.GetString("Amount", resourceCulture);
        public static string Employees => ResourceManager.GetString("Employees", resourceCulture);
        public static string TodaysAttendance => ResourceManager.GetString("TodaysAttendance", resourceCulture);
        public static string EmployeeID => ResourceManager.GetString("EmployeeID", resourceCulture);
        public static string AddMockPrinter => ResourceManager.GetString("AddMockPrinter", resourceCulture);
    }
}
