using System.Collections.Generic;

namespace Apex.Services.Printing.RIP.Models
{
    /// <summary>
    /// Profile describing the content of a single page.
    /// Generated by Content Analysis Engine to inform rendering decisions.
    /// </summary>
    public class PageContentProfile
    {
        /// <summary>
        /// Page index (0-based).
        /// </summary>
        public int PageIndex { get; set; }

        /// <summary>
        /// Whether the page contains text content.
        /// </summary>
        public bool HasText { get; set; }

        /// <summary>
        /// Whether the page contains vector graphics (paths, shapes, lines).
        /// </summary>
        public bool HasVectorGraphics { get; set; }

        /// <summary>
        /// Whether the page contains raster images.
        /// </summary>
        public bool HasImages { get; set; }

        /// <summary>
        /// Whether the page contains mixed content types.
        /// </summary>
        public bool IsMixedContent { get; set; }

        /// <summary>
        /// Number of text blocks detected.
        /// </summary>
        public int TextBlockCount { get; set; }

        /// <summary>
        /// Number of vector objects (paths, shapes) detected.
        /// </summary>
        public int VectorObjectCount { get; set; }

        /// <summary>
        /// Number of images detected.
        /// </summary>
        public int ImageCount { get; set; }

        /// <summary>
        /// Minimum resolution (DPI) of all images on the page.
        /// </summary>
        public double MinImageResolution { get; set; }

        /// <summary>
        /// Maximum resolution (DPI) of all images on the page.
        /// </summary>
        public double MaxImageResolution { get; set; }

        /// <summary>
        /// Average resolution (DPI) of all images on the page.
        /// </summary>
        public double AverageImageResolution { get; set; }

        /// <summary>
        /// Color profile information.
        /// </summary>
        public ColorProfileInfo ColorProfile { get; set; } = new();

        /// <summary>
        /// Whether this page requires rasterization (calculated).
        /// True only if images are present and cannot be handled natively.
        /// </summary>
        public bool RequiresRasterization { get; set; }

        /// <summary>
        /// Content complexity score (0-100).
        /// Higher = more complex, may require more processing.
        /// </summary>
        public int ComplexityScore { get; set; }

        /// <summary>
        /// List of detected fonts on the page.
        /// </summary>
        public List<string> Fonts { get; set; } = new();

        /// <summary>
        /// Page dimensions in points (1/72 inch).
        /// </summary>
        public PageDimensions Dimensions { get; set; } = new();
    }

    /// <summary>
    /// Color profile information.
    /// </summary>
    public class ColorProfileInfo
    {
        public bool IsColor { get; set; }
        public bool IsGrayscale { get; set; }
        public bool IsMonochrome { get; set; }
        public string? ColorSpace { get; set; } // RGB, CMYK, etc.
    }

    /// <summary>
    /// Page dimensions.
    /// </summary>
    public class PageDimensions
    {
        public double WidthPoints { get; set; }
        public double HeightPoints { get; set; }
        public string? PageSize { get; set; } // A4, Letter, etc.
    }
}
