using System;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace Apex.Licensing
{
    /// <summary>
    /// Handles ECDSA-P256 signing / verification and HMAC-SHA256 helpers.
    ///
    /// KEY SETUP (one-time, done by the developer / admin):
    ///   1. Run Apex.AdminTool with --genkeys  → saves private.pem + public.pem
    ///   2. Copy the content of public.pem into EmbeddedPublicKeyPem below.
    ///   3. Keep private.pem secret – use only in Apex.AdminTool.
    /// </summary>
    public static class LicenseCrypto
    {
        // ──────────────────────────────────────────────────────────────────
        //  Embedded Public Key
        //  Replace the placeholder below with the actual public key PEM
        //  generated by:  Apex.AdminTool --genkeys
        // ──────────────────────────────────────────────────────────────────
        internal const string EmbeddedPublicKeyPem =
            """
            -----BEGIN PUBLIC KEY-----
            MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQdWWaIUvv003N/mNSKcHrJtxJ+uu
            hukqhd2J0gvCjemeR0rQ9lxYQSexTDEFQR2vUh5+8tWBfm/MzNq0euSwOA==
            -----END PUBLIC KEY-----
            """;

        // Secret used to HMAC the trial state (obfuscated at rest; not cryptographic secrecy)
        private const string TrialHmacSecret = "Apex$Trial$2025$Secure!@#";

        // ──────────────────────────────────────────────────────────────────
        //  License signing (AdminTool only – requires private key)
        // ──────────────────────────────────────────────────────────────────

        /// <summary>
        /// Signs a <see cref="LicensePayload"/> with the supplied ECDSA private key.
        /// </summary>
        public static SignedLicense SignLicense(LicensePayload payload, ECDsa privateKey)
        {
            var payloadJson   = JsonSerializer.Serialize(payload, _jsonOpts);
            var payloadBytes  = Encoding.UTF8.GetBytes(payloadJson);
            var payloadBase64 = Convert.ToBase64String(payloadBytes);

            var signature = privateKey.SignData(
                Encoding.UTF8.GetBytes(payloadBase64),
                HashAlgorithmName.SHA256);

            return new SignedLicense
            {
                Payload       = payloadBase64,
                Signature     = Convert.ToBase64String(signature),
                SchemaVersion = "1"
            };
        }

        // ──────────────────────────────────────────────────────────────────
        //  License verification (embedded public key)
        // ──────────────────────────────────────────────────────────────────

        /// <summary>
        /// Verifies a <see cref="SignedLicense"/> using the embedded public key.
        /// Returns (true, payload) on success, (false, null) on any failure.
        /// </summary>
        public static (bool IsValid, LicensePayload? Payload) VerifyLicense(
            SignedLicense signedLicense,
            string?       publicKeyPemOverride = null)
        {
            try
            {
                var pem = publicKeyPemOverride ?? EmbeddedPublicKeyPem;

                // Bail fast if no real key has been embedded yet
                if (pem.Contains("PLACEHOLDER"))
                    return (false, null);

                using var ecdsa = ECDsa.Create();
                ecdsa.ImportFromPem(pem);

                var payloadBytes   = Encoding.UTF8.GetBytes(signedLicense.Payload);
                var signatureBytes = Convert.FromBase64String(signedLicense.Signature);

                if (!ecdsa.VerifyData(payloadBytes, signatureBytes, HashAlgorithmName.SHA256))
                    return (false, null);

                var jsonBytes = Convert.FromBase64String(signedLicense.Payload);
                var payload   = JsonSerializer.Deserialize<LicensePayload>(jsonBytes, _jsonOpts);
                return (true, payload);
            }
            catch
            {
                return (false, null);
            }
        }

        // ──────────────────────────────────────────────────────────────────
        //  Trial HMAC helpers
        // ──────────────────────────────────────────────────────────────────

        /// <summary>Computes HMAC-SHA256 of the trial state fields.</summary>
        public static string ComputeTrialHmac(TrialState state)
        {
            var data = $"{state.StartUtc.Ticks}|{state.LastSeenUtc.Ticks}|{state.DeviceId}";
            using var hmac = new HMACSHA256(Encoding.UTF8.GetBytes(TrialHmacSecret));
            var hash = hmac.ComputeHash(Encoding.UTF8.GetBytes(data));
            return Convert.ToBase64String(hash);
        }

        /// <summary>Returns true if the stored HMAC matches a freshly computed one.</summary>
        public static bool VerifyTrialHmac(TrialState state)
        {
            var expected = ComputeTrialHmac(state);
            // Constant-time compare
            return CryptographicOperations.FixedTimeEquals(
                Encoding.UTF8.GetBytes(state.Hmac),
                Encoding.UTF8.GetBytes(expected));
        }

        // ──────────────────────────────────────────────────────────────────
        //  Key generation (used by AdminTool)
        // ──────────────────────────────────────────────────────────────────

        /// <summary>
        /// Generates a fresh ECDSA-P256 key pair and exports PEM strings.
        /// </summary>
        public static (string PrivatePem, string PublicPem) GenerateKeyPair()
        {
            using var ecdsa = ECDsa.Create(ECCurve.NamedCurves.nistP256);
            return (ecdsa.ExportECPrivateKeyPem(), ecdsa.ExportSubjectPublicKeyInfoPem());
        }

        // ──────────────────────────────────────────────────────────────────
        //  Helpers
        // ──────────────────────────────────────────────────────────────────

        private static readonly JsonSerializerOptions _jsonOpts = new()
        {
            WriteIndented        = false,
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase
        };
    }
}
