<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Apex.NumberedBooksEngine\Apex.NumberedBooksEngine.csproj" />
    <ProjectReference Include="..\Apex.Services\Apex.Services.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PdfiumViewer" Version="2.13.0.0" />
    <PackageReference Include="PdfiumViewer.Native.x86_64.v8-xfa" Version="2018.4.8.256" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
